### PR TITLE
Using conda

### PR DESCRIPTION
**Pull request by emiliom**
Pasted text about conda rationale and installation from multiple sources, from echospace, OceanHackWeek or other text I've had a hand on. I haven't tried to massage any of it yet!

### CODE REVIEW

**Comment by emiliom** [comment]
A complete example of the steps to install and configure conda, on Linux:

```bash
url=https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
mkdir -p ~/miniconda3
wget $url -O ~/miniconda3/miniconda.sh
bash miniconda.sh -b -u -p ~/miniconda3
rm -rf ~/miniconda3/miniconda.sh

conda init
conda update -n base conda --yes

conda install -n base conda-libmamba-solver
conda config --set solver libmamba
```

See https://docs.conda.io/projects/miniconda/en/latest/#quick-command-line-install at least for the first set of commands.

**Comment by leewujung** [comment]
Hey @emiliom : Is this ready to be merged now? I pointed @varun-krishanumakr to this as he is learning conda and will need to start creating an environment soon, so can function as a good tester for the material. Thanks!

**Comment by emiliom** [comment]
It's not ready to merge, but really, it's been too long and I have everything I need. I'll finish it and merge it today. Plus it'll be good to have @varun-krishanumakr's input as he tries to use this intro & guidance.

**Comment by emiliom** [comment]
I've overhauled this PR. The content is now ready to go. I'll go ahead and merge it!

**Pull request merged**
